spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
